Create a 1D NumPy array containing the integers from 0 to 9.

In [1]:
import numpy as np

In [2]:
array_1d = np.arange(10)
print("1D Array:", array_1d)


1D Array: [0 1 2 3 4 5 6 7 8 9]


Create a 2D NumPy array (3x3) containing random integers between 1 and 20.

In [5]:
array_2d = np.random.randint(1, 21, size=(3, 3))
print("2D Array (3x3) with random integers between 1 and 20:\n", array_2d)

2D Array (3x3) with random integers between 1 and 20:
 [[ 7 13 14]
 [10 14  5]
 [20 17 10]]


Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.

In [6]:
array_3d = np.ones((2, 3, 4))
print("3D Array (2, 3, 4) filled with ones:\n", array_3d)

3D Array (2, 3, 4) filled with ones:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Add two 1D arrays element-wise.

In [7]:
array_1d_1 = np.array([1, 2, 3, 4, 5])
array_1d_2 = np.array([10, 20, 30, 40, 50])
array_sum = np.add(array_1d_1, array_1d_2)
print("Element-wise addition of two 1D arrays:", array_sum)

Element-wise addition of two 1D arrays: [11 22 33 44 55]


Multiply two 2D arrays element-wise.

In [8]:
array_2d_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d_2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
array_mult = np.multiply(array_2d_1, array_2d_2)
print("Element-wise multiplication of two 2D arrays:\n", array_mult)

Element-wise multiplication of two 2D arrays:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


Calculate the dot product of two matrices

In [9]:
array_matrix_1 = np.array([[1, 2], [3, 4]])
array_matrix_2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(array_matrix_1, array_matrix_2)
print("Dot product of two matrices:\n", dot_product)

Dot product of two matrices:
 [[19 22]
 [43 50]]


Calculate the mean, median, and standard deviation of a 1D array

In [10]:
array_stats = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(array_stats)
median = np.median(array_stats)
std_dev = np.std(array_stats)
print("Mean:", mean, "Median:", median, "Standard Deviation:", std_dev)

Mean: 5.5 Median: 5.5 Standard Deviation: 2.8722813232690143


Find the maximum and minimum values in a 2D array.

In [11]:
array_2d_max_min = np.random.randint(1, 101, size=(5, 5))
max_value = np.max(array_2d_max_min)
min_value = np.min(array_2d_max_min)
print("2D Array:\n", array_2d_max_min)
print("Maximum value:", max_value, "Minimum value:", min_value)

2D Array:
 [[ 16  36  11  25  36]
 [ 29  16   7  70  31]
 [ 35   9  68  80  35]
 [  9 100  83   3  13]
 [ 87  25  99  53  93]]
Maximum value: 100 Minimum value: 3


Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.

In [12]:
array_normal_dist = np.random.normal(0, 1, 1000)
print("Array of 1000 random numbers from a normal distribution:\n", array_normal_dist)

Array of 1000 random numbers from a normal distribution:
 [ 1.21218315e+00  2.49592715e-01  2.98879503e-01  1.14973097e+00
  3.47952101e-01  7.92320749e-01 -1.00907690e-01 -4.79970813e-01
  7.02294436e-01  7.95687477e-01  1.05818223e+00  1.48155985e+00
 -5.52738217e-01 -4.33337447e-01  1.41481175e+00  4.27672204e-01
 -2.98630193e-02 -1.20751497e+00 -3.15095848e-01  1.48350922e+00
 -9.86211652e-01  9.99546941e-01 -3.53121061e-01  5.17667246e-03
 -7.48833975e-01 -6.23398602e-01 -1.66461945e-01 -7.71909694e-01
  5.65488513e-01 -6.61541259e-01 -8.50351162e-01  8.21512076e-01
 -1.11318180e+00  1.12690279e+00  2.06549563e+00 -3.06958655e-01
  1.55132690e+00 -9.03856882e-01 -1.23505598e+00  5.50090131e-01
 -1.08623760e+00 -9.22276948e-01 -5.28339758e-01 -7.06841576e-01
 -9.25848053e-01 -4.01870797e-02 -1.64294458e-01  8.93045985e-01
  5.60715928e-01 -2.55540050e+00 -1.42064951e+00 -9.43363549e-01
 -7.88842513e-01  8.60214229e-01  1.04617487e+00  3.88233241e-01
 -1.34928570e+00  7.96862389e-01

 Create a 2D array of shape (5, 5) with random integers from a uniform distribution between 10 and 50.

In [13]:
array_uniform_dist = np.random.randint(10, 51, size=(5, 5))
print("2D Array of shape (5, 5) with random integers from 10 to 50:\n", array_uniform_dist)

2D Array of shape (5, 5) with random integers from 10 to 50:
 [[44 35 15 43 30]
 [29 23 17 11 14]
 [10 50 23 48 20]
 [22 34 45 20 26]
 [24 32 31 30 25]]


Calculate the cumulative sum of a 1D array.

In [14]:
array_cumsum = np.cumsum(array_stats)
print("Cumulative sum of 1D array:", array_cumsum)

Cumulative sum of 1D array: [ 1  3  6 10 15 21 28 36 45 55]


Compute the correlation coefficient matrix of a 2D array.

In [15]:
array_corr = np.random.rand(5, 5)
correlation_matrix = np.corrcoef(array_corr)
print("2D Array for correlation:\n", array_corr)
print("Correlation coefficient matrix:\n", correlation_matrix)

2D Array for correlation:
 [[0.17248496 0.63543408 0.52595341 0.61686425 0.28642198]
 [0.60910182 0.6266674  0.52153823 0.66760489 0.20169546]
 [0.52641893 0.89550183 0.20917675 0.82691485 0.21669295]
 [0.6600289  0.09842304 0.99052988 0.71607995 0.97668296]
 [0.77949325 0.12234747 0.52224517 0.79140807 0.69864402]]
Correlation coefficient matrix:
 [[ 1.          0.46018643  0.53911821 -0.40373905 -0.55664417]
 [ 0.46018643  1.          0.74045593 -0.55910798 -0.17944183]
 [ 0.53911821  0.74045593  1.         -0.83832141 -0.34162429]
 [-0.40373905 -0.55910798 -0.83832141  1.          0.71044761]
 [-0.55664417 -0.17944183 -0.34162429  0.71044761  1.        ]]


Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.

In [16]:
rolls = np.random.randint(1, 7, 1000)
outcome_counts = np.bincount(rolls)[1:]  
print("Frequency of each outcome in 1000 rolls of a six-sided die:", outcome_counts)

Frequency of each outcome in 1000 rolls of a six-sided die: [140 166 180 181 154 179]
