# Task 21

### Linear Algebra

Create various types of matrices (zero matrix, identity matrix, random matrix).

In [3]:
import numpy as np

# Zero matrix...
zero_matrix = np.zeros((3, 3))

# Identity matrix...
identity_matrix = np.eye(3)

# Random matrix...
random_matrix = np.random.rand(3, 3)

zero_matrix, identity_matrix, random_matrix


(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[0.23942733, 0.01227528, 0.06663231],
        [0.24004925, 0.4328014 , 0.86619721],
        [0.44255876, 0.77000249, 0.49859014]]))

Perform basic matrix operations (addition, subtraction, multiplication)

In [4]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Addition...
matrix_add = matrix_a + matrix_b

# Subtraction...
matrix_subtract = matrix_a - matrix_b

# Multiplication...
matrix_multiply = np.dot(matrix_a, matrix_b)

matrix_add, matrix_subtract, matrix_multiply


(array([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]),
 array([[-8, -6, -4],
        [-2,  0,  2],
        [ 4,  6,  8]]),
 array([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]]))

Transpose a matrix and find the determinant and inverse of a matrix.

In [5]:
matrix = np.array([[1, 2], [3, 4]])

# Transpose...
matrix_transpose = matrix.T

# Determinant...
matrix_determinant = np.linalg.det(matrix)

# Inverse...
matrix_inverse = np.linalg.inv(matrix)

matrix_transpose, matrix_determinant, matrix_inverse


(array([[1, 3],
        [2, 4]]),
 -2.0000000000000004,
 array([[-2. ,  1. ],
        [ 1.5, -0.5]]))

### Solving Linear Equation 


Use NumPy to solve a system of linear equations.

In [7]:
# System of equations:...
# 6x + 3y = 8
# 1x + 2y = 5

coefficients = np.array([[6, 3], [1, 2]])
constants = np.array([8, 5])

solution = np.linalg.solve(coefficients, constants)
solution


array([0.11111111, 2.44444444])

Implement matrix factorization methods (LU decomposition, QR decomposition).
python

In [8]:
# LU Decomposition...
from scipy.linalg import lu

P, L, U = lu(matrix)
P, L, U

# QR Decomposition...
Q, R = np.linalg.qr(matrix)
Q, R


(array([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]),
 array([[-3.16227766, -4.42718872],
        [ 0.        , -0.63245553]]))

### Eigenvalues and Eigenvectors

Calculate the eigenvalues and eigenvectors of a given matrix.

In [9]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)
eigenvalues, eigenvectors


(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

Verify the results by reconstructing the original matrix.

In [10]:
# Reconstructing the original matrix...
reconstructed_matrix = eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)
reconstructed_matrix


array([[1., 2.],
       [3., 4.]])

### Vector Operation

Perform basic vector operations (addition, dot product, cross product).

In [11]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Addition...
vector_add = vector_a + vector_b

# Dot product...
vector_dot = np.dot(vector_a, vector_b)

# Cross product...
vector_cross = np.cross(vector_a, vector_b)

vector_add, vector_dot, vector_cross


(array([5, 7, 9]), 32, array([-3,  6, -3]))

Normalize a vector and compute vector norms

In [12]:
# Normalize a vector...
vector_norm = np.linalg.norm(vector_a)
vector_normalized = vector_a / vector_norm

# Compute vector norms...
vector_l1_norm = np.linalg.norm(vector_a, 1)
vector_l2_norm = np.linalg.norm(vector_a, 2)

vector_normalized, vector_l1_norm, vector_l2_norm


(array([0.26726124, 0.53452248, 0.80178373]), 6.0, 3.7416573867739413)

### Matrix Decomposition

Understand and implement Principal Component Analysis (PCA) using SVD.

In [13]:
from sklearn.decomposition import PCA

data = np.random.rand(10, 5)
pca = PCA(n_components=2)
pca_result = pca.fit_transform(data)

pca_result


array([[ 0.4448852 , -0.17627238],
       [-0.13060304,  0.50941549],
       [ 0.397237  ,  0.20448738],
       [-0.11658766, -0.32507829],
       [-0.6412701 , -0.18367033],
       [-0.2649743 ,  0.47173915],
       [-0.10456362, -0.50120362],
       [ 0.0194418 ,  0.09082298],
       [-0.26375133, -0.04160518],
       [ 0.66018604, -0.0486352 ]])

## Calculus Tasks

### Numerical Differentiation

Use NumPy to compute the numerical derivative of a given function.

In [14]:
def f(x):
    return x**2 + 2*x + 1

x = np.linspace(-10, 10, 100)
y = f(x)

# Numerical derivative using central difference...
dx = x[1] - x[0]
dy = np.gradient(y, dx)

dy


array([-17.7979798 , -17.5959596 , -17.19191919, -16.78787879,
       -16.38383838, -15.97979798, -15.57575758, -15.17171717,
       -14.76767677, -14.36363636, -13.95959596, -13.55555556,
       -13.15151515, -12.74747475, -12.34343434, -11.93939394,
       -11.53535354, -11.13131313, -10.72727273, -10.32323232,
        -9.91919192,  -9.51515152,  -9.11111111,  -8.70707071,
        -8.3030303 ,  -7.8989899 ,  -7.49494949,  -7.09090909,
        -6.68686869,  -6.28282828,  -5.87878788,  -5.47474747,
        -5.07070707,  -4.66666667,  -4.26262626,  -3.85858586,
        -3.45454545,  -3.05050505,  -2.64646465,  -2.24242424,
        -1.83838384,  -1.43434343,  -1.03030303,  -0.62626263,
        -0.22222222,   0.18181818,   0.58585859,   0.98989899,
         1.39393939,   1.7979798 ,   2.2020202 ,   2.60606061,
         3.01010101,   3.41414141,   3.81818182,   4.22222222,
         4.62626263,   5.03030303,   5.43434343,   5.83838384,
         6.24242424,   6.64646465,   7.05050505,   7.45

Implement forward, backward, and central difference methods for differentiation.

In [15]:
# Forward difference...
def forward_difference(f, x, h=1e-5):
    return (f(x + h) - f(x)) / h

# Backward difference...
def backward_difference(f, x, h=1e-5):
    return (f(x) - f(x - h)) / h

# Central difference...
def central_difference(f, x, h=1e-5):
    return (f(x + h) - f(x - h)) / (2 * h)

forward_diff = forward_difference(f, x)
backward_diff = backward_difference(f, x)
central_diff = central_difference(f, x)

forward_diff, backward_diff, central_diff


(array([-17.99999   , -17.59594959, -17.19190919, -16.78786879,
        -16.38382838, -15.97978798, -15.57574757, -15.17170717,
        -14.76766677, -14.36362636, -13.95958596, -13.55554556,
        -13.15150515, -12.74746475, -12.34342434, -11.93938394,
        -11.53534353, -11.13130313, -10.72726273, -10.32322232,
         -9.91918192,  -9.51514152,  -9.11110111,  -8.70706071,
         -8.3030203 ,  -7.8989799 ,  -7.49493949,  -7.09089909,
         -6.68685869,  -6.28281828,  -5.87877788,  -5.47473747,
         -5.07069707,  -4.66665667,  -4.26261626,  -3.85857586,
         -3.45453545,  -3.05049505,  -2.64645465,  -2.24241424,
         -1.83837384,  -1.43433343,  -1.03029303,  -0.62625263,
         -0.22221222,   0.18182818,   0.58586859,   0.98990899,
          1.39394939,   1.7979898 ,   2.2020302 ,   2.60607061,
          3.01011101,   3.41415141,   3.81819182,   4.22223222,
          4.62627263,   5.03031303,   5.43435343,   5.83839384,
          6.24243424,   6.64647465,   7.

### Numerical Integration

Use NumPy to compute the numerical integral of a given function.

In [16]:
def g(x):
    return np.sin(x)

# Numerical integration using trapezoidal rule...
integral_trapezoidal = np.trapz(g(x), x)

integral_trapezoidal


-4.163336342344337e-17

Implement the trapezoidal rule and Simpson's rule for integration.

In [17]:
from scipy.integrate import simps

# Trapezoidal rule...
def trapezoidal_rule(f, a, b, n):
    x = np.linspace(a, b, n)
    y = f(x)
    return np.trapz(y, x)

# Simpson's rule...
def simpsons_rule(f, a, b, n):
    x = np.linspace(a, b, n)
    y = f(x)
    return simps(y, x)

a, b, n = 0, np.pi, 100

trapezoidal_result = trapezoidal_rule(g, a, b, n)
simpsons_result = simpsons_rule(g, a, b, n)

trapezoidal_result, simpsons_result


C:\Users\kkrab\AppData\Local\Temp\ipykernel_11320\1289110512.py:13: DeprecationWarning: 'scipy.integrate.simps' is deprecated in favour of 'scipy.integrate.simpson' and will be removed in SciPy 1.14.0
  return simps(y, x)


(1.9998321638939927, 2.0000000534993037)

### Partial Derivatives

Calculate partial derivatives of multivariable functions using NumPy.

In [18]:
def h(x, y):
    return x**2 + y**2

def partial_x(f, x, y, h=1e-5):
    return (f(x + h, y) - f(x - h, y)) / (2 * h)

def partial_y(f, x, y, h=1e-5):
    return (f(x, y + h) - f(x, y - h)) / (2 * h)

x_val, y_val = 1.0, 2.0
partial_x_val = partial_x(h, x_val, y_val)
partial_y_val = partial_y(h, x_val, y_val)

partial_x_val, partial_y_val


(2.0000000000131024, 4.000000000026205)

Verify results by comparing with analytical solutions.

In [19]:
analytical_partial_x = 2 * 1
analytical_partial_y = 2 * 2

(partial_x, analytical_partial_x), (partial_y, analytical_partial_y)


((<function __main__.partial_x(f, x, y, h=1e-05)>, 2),
 (<function __main__.partial_y(f, x, y, h=1e-05)>, 4))

### Optimization

Use NumPy to solve optimization problems with constraints.


In [20]:
from scipy.optimize import minimize

# Objective function...
def objective(x):
    return x[0]**2 + x[1]**2

# Constraints....
cons = ({'type': 'eq', 'fun': lambda x: x[0] + x[1] - 1})

# Initial guess...
x0 = [0.5, 0.5]

# Solve optimization...
result = minimize(objective, x0, constraints=cons)

result.x


array([0.5, 0.5])