# Indexing 


Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1).

In [2]:
import numpy as np

In [3]:
array_2d_6x6 = np.arange(1, 37).reshape(6, 6)
sub_array_2x2 = array_2d_6x6[1:3, 1:3]
print("Original 2D array (6x6):\n", array_2d_6x6)
print("Extracted 2x2 sub-array:\n", sub_array_2x2)

Original 2D array (6x6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Extracted 2x2 sub-array:
 [[ 8  9]
 [14 15]]


From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axis.

In [4]:
array_3d = np.arange(1, 7).reshape(3, 2, 1)
sub_array_3d = array_3d[:2, :, 0]
print("Original 3D array (3, 2, 1):\n", array_3d)
print("Extracted elements:\n", sub_array_3d)

Original 3D array (3, 2, 1):
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
Extracted elements:
 [[1 2]
 [3 4]]


Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 6].

In [5]:
array_int = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
fancy_indexing_result = array_int[[1, 3, 4, 6]]
print("Array of integers:", array_int)
print("Elements at positions [1, 3, 4, 6]:", fancy_indexing_result)

Array of integers: [0 1 2 3 4 5 6 7 8 9]
Elements at positions [1, 3, 4, 6]: [1 3 4 6]


Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3].


In [6]:
array_2d_fancy = np.arange(1, 17).reshape(4, 4)
fancy_indexing_2d_result = array_2d_fancy[[0, 2, 2], [1, 3, 3]]
print("Original 2D array:\n", array_2d_fancy)
print("Selected elements using fancy indexing:", fancy_indexing_2d_result)

Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Selected elements using fancy indexing: [ 2 12 12]


From a 1D array of random integers, extract all elements that are greater than 8.

In [7]:
array_random_int = np.random.randint(1, 20, 15)
greater_than_8 = array_random_int[array_random_int > 8]
print("Array of random integers:", array_random_int)
print("Elements greater than 8:", greater_than_8)

Array of random integers: [ 9 13  8  6  7  8  7 19  5  1 14  3 17  6  7]
Elements greater than 8: [ 9 13 19 14 17]


Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0.

In [8]:
array_2d_replace = np.random.randint(1, 20, (6, 6))
array_2d_replace[array_2d_replace > 13] = 0
print("Original 2D array:\n", array_2d_replace)
print("Array after replacing elements greater than 13 with 0:\n", array_2d_replace)

Original 2D array:
 [[ 0  0  1  4  0  9]
 [ 8  0  0  9  8  9]
 [ 0  2  0  0  4  3]
 [ 0  0  9 12 11  0]
 [ 0 12  0 11 10  7]
 [ 4 12  4 13  0  3]]
Array after replacing elements greater than 13 with 0:
 [[ 0  0  1  4  0  9]
 [ 8  0  0  9  8  9]
 [ 0  2  0  0  4  3]
 [ 0  0  9 12 11  0]
 [ 0 12  0 11 10  7]
 [ 4 12  4 13  0  3]]


# Broadcasting

Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).

In [9]:
array_1d_broadcast = np.array([1, 2, 3])
array_2d_broadcast = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
broadcast_result = array_2d_broadcast + array_1d_broadcast
print("1D array:", array_1d_broadcast)
print("2D array:\n", array_2d_broadcast)
print("Result after broadcasting:\n", broadcast_result)

1D array: [1 2 3]
2D array:
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Result after broadcasting:
 [[ 5  7  9]
 [ 8 10 12]
 [11 13 15]
 [14 16 18]]


 Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).

In [10]:
array_2d_mult = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_1d_mult = np.array([2, 4, 6])
mult_result = array_2d_mult * array_1d_mult
print("2D array:\n", array_2d_mult)
print("1D array:", array_1d_mult)
print("Result after element-wise multiplication:\n", mult_result)

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1D array: [2 4 6]
Result after element-wise multiplication:
 [[ 2  8 18]
 [ 8 20 36]
 [14 32 54]]


Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.

In [11]:
array_2d_3x1 = np.array([[1], [2], [3]])
array_2d_1x4 = np.array([[10, 20, 30, 40]])
elementwise_addition = array_2d_3x1 + array_2d_1x4
print("2D array (3, 1):\n", array_2d_3x1)
print("2D array (1, 4):\n", array_2d_1x4)
print("Result after element-wise addition:\n", elementwise_addition)

2D array (3, 1):
 [[1]
 [2]
 [3]]
2D array (1, 4):
 [[10 20 30 40]]
Result after element-wise addition:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.

In [12]:
array_3d_broadcast = np.random.randint(1, 10, (2, 3, 4))
array_2d_broadcast_3d = np.random.randint(1, 10, (3, 4))
broadcast_result_3d = array_3d_broadcast + array_2d_broadcast_3d
print("3D array (2, 3, 4):\n", array_3d_broadcast)
print("2D array (3, 4):\n", array_2d_broadcast_3d)
print("Result after broadcasting to each 2D slice:\n", broadcast_result_3d)

3D array (2, 3, 4):
 [[[8 6 8 3]
  [1 6 4 6]
  [7 7 7 9]]

 [[7 4 1 9]
  [2 4 7 1]
  [5 7 3 8]]]
2D array (3, 4):
 [[1 9 5 9]
 [2 4 8 3]
 [5 5 8 1]]
Result after broadcasting to each 2D slice:
 [[[ 9 15 13 12]
  [ 3 10 12  9]
  [12 12 15 10]]

 [[ 8 13  6 18]
  [ 4  8 15  4]
  [10 12 11  9]]]


Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.

In [13]:
array_2d_more = np.random.randint(1, 10, (6, 6))
sliced_array = array_2d_more[::2, ::2]
array_1d_more = np.array([1, 2, 3])
sliced_array_result = sliced_array + array_1d_more
print("Original 2D array:\n", array_2d_more)
print("Sliced array (every second row and column):\n", sliced_array)
print("1D array:", array_1d_more)
print("Result after addition:\n", sliced_array_result)

Original 2D array:
 [[7 3 5 3 4 9]
 [9 5 6 8 7 5]
 [7 6 8 9 1 1]
 [3 9 2 2 2 6]
 [4 3 7 1 7 2]
 [1 1 5 6 4 1]]
Sliced array (every second row and column):
 [[7 5 4]
 [7 8 1]
 [4 7 7]]
1D array: [1 2 3]
Result after addition:
 [[ 8  7  7]
 [ 8 10  4]
 [ 5  9 10]]


From a 3D array of shape (3, 2, 1), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

In [14]:
array_3d_more = np.random.randint(1, 10, (3, 2, 1))
sub_array_3d_more = array_3d_more[:, :, 0]
array_2d_more_sub = np.array([[1, 2], [3, 4], [5, 6]])
broadcast_sub_result = sub_array_3d_more - array_2d_more_sub
print("Original 3D array:\n", array_3d_more)
print("Sub-array using slicing:\n", sub_array_3d_more)
print("2D array to subtract:\n", array_2d_more_sub)
print("Result after broadcasting subtraction:\n", broadcast_sub_result)

Original 3D array:
 [[[3]
  [7]]

 [[8]
  [6]]

 [[8]
  [9]]]
Sub-array using slicing:
 [[3 7]
 [8 6]
 [8 9]]
2D array to subtract:
 [[1 2]
 [3 4]
 [5 6]]
Result after broadcasting subtraction:
 [[2 5]
 [5 2]
 [3 3]]


Given a 2D array, extract the diagonal elements and create a 1D array

In [15]:
array_2d_diag = np.random.randint(1, 10, (5, 5))
diagonal_elements = np.diag(array_2d_diag)
print("Original 2D array:\n", array_2d_diag)
print("Diagonal elements:", diagonal_elements)

Original 2D array:
 [[8 3 5 9 1]
 [7 4 6 1 7]
 [5 2 9 6 3]
 [6 6 4 6 1]
 [2 3 5 9 5]]
Diagonal elements: [8 4 9 6 5]


Use slicing to reverse the order of elements in each row of a 2D array.

In [16]:
array_2d_reverse = np.random.randint(1, 10, (4, 4))
reversed_array = array_2d_reverse[:, ::-1]
print("Original 2D array:\n", array_2d_reverse)
print("Array with elements in each row reversed:\n", reversed_array)

Original 2D array:
 [[3 5 2 4]
 [7 6 9 5]
 [4 7 1 7]
 [6 1 3 8]]
Array with elements in each row reversed:
 [[4 2 5 3]
 [5 9 6 7]
 [7 1 7 4]
 [8 3 1 6]]


Given a 3D array of shape (7, 6, 5), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.

In [17]:
array_3d_large = np.random.randint(1, 10, (7, 6, 5))
sub_array_3d_large = array_3d_large[:2, :3, :4]
array_1d_add_large = np.array([1, 2, 3, 4])
broadcast_result_large = sub_array_3d_large + array_1d_add_large
print("Original 3D array (7, 6, 5):\n", array_3d_large)
print("Extracted sub-array (2, 3, 4):\n", sub_array_3d_large)
print("1D array to add:", array_1d_add_large)
print("Result after broadcasting addition:\n", broadcast_result_large)

Original 3D array (7, 6, 5):
 [[[5 9 2 4 6]
  [6 5 4 9 7]
  [1 5 6 1 3]
  [1 8 1 8 2]
  [2 6 8 8 4]
  [1 9 1 5 8]]

 [[2 7 2 4 2]
  [8 1 5 2 1]
  [6 4 2 5 2]
  [3 7 4 7 2]
  [1 7 4 2 2]
  [2 9 9 7 4]]

 [[8 6 6 5 2]
  [1 1 9 4 7]
  [6 2 8 6 6]
  [1 4 5 2 6]
  [8 3 1 6 7]
  [4 8 5 5 5]]

 [[1 3 6 4 3]
  [7 7 5 6 9]
  [8 5 9 1 5]
  [2 4 3 4 7]
  [4 4 1 9 5]
  [6 2 2 6 4]]

 [[9 6 4 7 8]
  [6 8 9 4 2]
  [2 3 8 7 6]
  [1 4 9 9 7]
  [4 7 8 3 5]
  [9 1 6 6 9]]

 [[2 4 3 2 6]
  [9 7 8 3 9]
  [9 8 6 1 2]
  [8 7 4 7 2]
  [9 2 2 2 1]
  [5 6 9 7 9]]

 [[9 2 1 3 1]
  [5 3 8 8 1]
  [8 2 6 1 9]
  [5 4 6 2 9]
  [3 3 2 9 6]
  [9 1 3 6 4]]]
Extracted sub-array (2, 3, 4):
 [[[5 9 2 4]
  [6 5 4 9]
  [1 5 6 1]]

 [[2 7 2 4]
  [8 1 5 2]
  [6 4 2 5]]]
1D array to add: [1 2 3 4]
Result after broadcasting addition:
 [[[ 6 11  5  8]
  [ 7  7  7 13]
  [ 2  7  9  5]]

 [[ 3  9  5  8]
  [ 9  3  8  6]
  [ 7  6  5  9]]]


Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.

In [18]:
array_2d_sum_cols = np.random.randint(1, 10, (5, 5))
array_2d_sum_cols[:, -1] = array_2d_sum_cols[:, 0] + array_2d_sum_cols[:, 1]
print("Original 2D array:\n", array_2d_sum_cols)
print("Array after setting the last column to the sum of the first two columns:\n", array_2d_sum_cols)

Original 2D array:
 [[ 2  3  9  8  5]
 [ 2  6  5  6  8]
 [ 5  5  5  4 10]
 [ 3  5  6  8  8]
 [ 5  9  3  5 14]]
Array after setting the last column to the sum of the first two columns:
 [[ 2  3  9  8  5]
 [ 2  6  5  6  8]
 [ 5  5  5  4 10]
 [ 3  5  6  8  8]
 [ 5  9  3  5 14]]
